### PR TITLE
Don't check outdated logs

### PR DESCRIPTION
**Pull request by erbkaiser**
Ignore outdated log files (redscript backups redscript_r{date}.log) and red4ext rollovers) and also check for errors in redmodlog.txt and potentially other log.txt files

### CODE REVIEW

**Comment by DoctorPresto** [comment]
Thanks for the PR! Is there a reason you chose not to just use findstr and Regex on line 189+? It's been a while since I had needed to look at redscript logs, are these not formatted as example.1.log or was that only CET that used that format?

**Comment by erbkaiser** [comment]
It's mainly so it will also skip the redscript backup logs, which are formatted as redscript_r2024-01-27_16-05-07.log
Each new launch copies the existing redscript_rCURRENT.log to one with the time and date stamp, so if there is an error, the batch script would report it for every single backup.

I don't think redscript clears these so unless someone runs option 1 first, they can end up with the script checking dozens (or more) of files needlessly.

Red4ext logs roll over where red4ext.log is copied to red4ext.1.log, and red4ext.1.log is copied to red4ext.2.log etc.

**Comment by erbkaiser** [comment]
As for not using findstr and regex, I suck at regex and could not get it to work, but this method works :D

**Comment by DoctorPresto** [comment]
Sorry, also is that section for old red4ext logs? They should already be ignored

**Comment by erbkaiser** [comment]
This is an example (edited for brevity) FilteredLogs.txt without the changes to the .bat:

[FilteredLogs.txt](https://github.com/DoctorPresto/Cyberpunk-Helper-Scripts/files/14072830/FilteredLogs.txt)

Notice how it doubles the error logs for the redscript log and the TweakXL log

**Comment by DoctorPresto** [comment]
> Red4ext logs roll over where red4ext.log is copied to red4ext.1.log, and red4ext.1.log is copied to red4ext.2.log etc.

These are already ignored, can you remove this block?

**Comment by erbkaiser** [comment]
Sorry, that is beyond my skills with batch scripting. If you can figure out a better way to filter out old redscript logs and TweakXL/ArchiveXL/other red4ext plugin logs, please do!

**Comment by DoctorPresto** [comment]
Sorry, what I mean is that old red4ext logs are already ignored. Archivexl/tweakxl just overwrite the same log file each time they're run.

**Comment by erbkaiser** [comment]
That must have changed then, since I am definitely getting error log rollover for TweakXL and other files. See the FilteredLogs.txt I uploaded as an example.

**Comment by erbkaiser** [comment]
Apologies for the delay.
Your code did not work as expected so I rewrote it a bit, it now seems to filter out all 'date stamped' logfiles.

**Comment by DoctorPresto** [comment]
No worries, I wrote the earlier on my phone so no doubt that it had some problems. Thanks for this! Lgtm

**Pull request merged**
